### ISSUE TITLE
pram: cron job for flask back end models

### ISSUE THREAD

**Issue by puruckertom** [quanted/qed#161]

**Comment by dbsmith88** [comment]
Updated flask shell script to run the pytests prior to standing up flask, output html are copied to shared docker volume, django pram qaqc updated to render html file from shared volume reports directory. All functionality working on server 7, qed_pram. Will merge updates into staging for testing on qedinternal.

**Comment by dbsmith88** [comment]
Updates added to server 1, successfully runs pytests on flask startup and pushes html reports to shared volume.
