### ISSUE TITLE
qed: handle 404s (django 2.0)

### ISSUE THREAD

**Issue by puruckertom** [quanted/qed#171]

**Comment by dbsmith88** [comment]
Updates have been pushed dev branch (requires updates of static_qed, templates_qed, splash_app, and qed)

**Comment by dbsmith88** [comment]
After fixing debug=true issue on server 3, the 404 issue had to be resolved using the handler404 instead of a url catch all (as the catch all prevents the append_slash setting from working properly). The handler404 does not run when debug=true.
